@startuml

component service {

	component TableCleanerScriptGenerator

}

component console {

	component CleanScriptCreator

	component DataModelToTableCleanerModelConverter
	
	component ScriptWriter
	
	CleanScriptCreateCommand -DOWN-> DataModelToTableCleanerModelConverter
	CleanScriptCreateCommand -DOWN-> ScriptWriter
	CleanScriptCreateCommand -DOWN-> TableCleanerScriptGenerator

}

@enduml