@startuml

CleanScriptCreateCommand -> DataModelToTableCleanerModelConverter : convert(dataModel)
CleanScriptCreateCommand <-- DataModelToTableCleanerModelConverter : tableCleanerModel

CleanScriptCreateCommand -> TableCleanerScriptGenerator : generateCleanScriptFor(tableCleanerModel)
CleanScriptCreateCommand <-- TableCleanerScriptGenerator : scriptModel

CleanScriptCreateCommand -> ScriptWriter : createScript(scriptModel)

@enduml